project:
  type: website
  execute-dir: project

website:
  title: "proPower"
  navbar:
    tools:
      - icon: github
        href: "https://github.com/stefanocoretta/proPower"
    left:
      - href: index.qmd
        text: Home
      - href: slides/
        text: Slides

format:
  html:
    theme:
      - flatly
    css: styles.css
    toc: true

execute:
  freeze: auto

