project:
  type: website
  execute-dir: project

website:
  title: "proPower"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: slides/
        text: Slides

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

execute:
  freeze: auto
  cache: true

