---
title: "proPower"
---

This is the website of the workshop *Prospective power analyses for frequentist regression models*, part of the [STeW](https://uoelel.github.io/stew.html) series (Statistical Training Workshops) of the Linguistics and English Language department of the University of Edinburgh.

The slides are linked in the main menu and you can find data and code in the GitHub repository: <https://github.com/stefanocoretta/proPower>.

|  |  |
|----------------|--------------------------------------------------------|
| **Level** | 🟠 Intermediate |
| **Description** | You will learn how to perform prospective power analyses for regression/linear models fitted with the frequentist lme4 package. Power analyses are a necessary (albeit always neglected) component of frequentist analyses, since they help the researcher determine the required sample size. Much of the replicability crisis we are facing is due to lack of statistical power (aka low sample sizes) in virtually all published studies. |
| **Prerequisites** | Need to be familiar with regression/linear models in R including models with random effects and binomial/Bernoulli (aka logistic) regressions. |
